spring:
  cloud:
    gateway:
      routes:
        - id: hotels-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/hotels/**
        - id: reserve-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/reserves/**
        - id: notification-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/emails/**
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true