spring:
  config:
    import: env.properties
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}

server:
  port: ${SERVER_PORT}

notification:
  api:
    url: ${NOTIFICATION_API_URL}
  email:
    from: ${NOTIFICATION_EMAIL_FROM}